# Generated by Django 2.2.5 on 2020-10-11 17:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20201011_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 17, 49, 31, 251579, tzinfo=utc)),
        ),
    ]
