# Generated by Django 2.2.5 on 2020-10-22 14:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20201020_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 22, 14, 26, 26, 272533, tzinfo=utc)),
        ),
    ]
