# Generated by Django 2.2.5 on 2020-11-03 09:48

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['groupName'],
            },
        ),
        migrations.CreateModel(
            name='OtherConstraints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minGradeTheoryConv', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('minGradeLabConv', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('selectGroupStartDate', models.DateTimeField(default=datetime.datetime(2020, 11, 3, 9, 48, 17, 37984, tzinfo=utc))),
            ],
            options={
                'verbose_name_plural': 'Other Constraints',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gradeTheoryLastYear', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('gradeLabLastYear', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('convalidationGranted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='LabGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Group')),
                ('schedule', models.CharField(max_length=50)),
                ('maxNumberStudents', models.IntegerField(default=0)),
                ('counter', models.IntegerField(default=0)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Teacher')),
            ],
            bases=('core.group',),
        ),
        migrations.CreateModel(
            name='TheoryGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Group')),
            ],
            bases=('core.group',),
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated', models.BooleanField(default=False)),
                ('student1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student1', to='core.Student')),
                ('student2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student2', to='core.Student')),
                ('studentBreakRequest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentBreakRequest', to='core.Student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='labGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.LabGroup'),
        ),
        migrations.AddField(
            model_name='student',
            name='theoryGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.TheoryGroup'),
        ),
        migrations.CreateModel(
            name='GroupConstraints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LabGroup')),
                ('theoryGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TheoryGroup')),
            ],
            options={
                'verbose_name_plural': 'Group Constraints',
                'ordering': ['labGroup', 'theoryGroup'],
            },
        ),
    ]
