# Generated by Django 2.2.5 on 2020-11-03 09:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherconstraints',
            name='selectGroupStartDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 9, 49, 10, 172195, tzinfo=utc)),
        ),
    ]
