# Generated by Django 2.2.5 on 2020-11-03 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201103_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherconstraints',
            name='selectGroupStartDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
