# Small script to plot the data generated by data.sh
gnuplot << END_GNUPLOT
set title "Function Calls Regular Minimax Vs AlphaBeta Pruning (Depth 4)"
set ylabel "# Function calls"
set xlabel "# move"
set key right top
set grid
set term png
set output "plot_depth4_calls.png"
plot "depth4_times_regular_p1.dat" using 1:2 with lines lw 2 title "Regular - Player 1", \
	"depth4_times_regular_p2.dat" using 1:2 with lines lw 2 title "Regular - Player 2", \
	"depth4_times_pruning_p1.dat" using 1:2 with lines lw 2 title "Pruning - Player 1", \
	"depth4_times_pruning_p2.dat" using 1:2 with lines lw 2 title "Pruning - Player 2"
    
replot
quit
END_GNUPLOT