ayuda_retro:
	@python3 src/main.py -h

compilar:
	@echo "Conectándose a las mainframes de facebook..."
	@sleep 3
	@echo "Ejecutando algoritmos de compilación cuántica..."
	@sleep 5
	@echo "Empaquetando..."
	@sleep 1
	@echo "Desplegando microservicios..."
	@sleep 1
	@echo "DONE"


ejecuta_problema_real2:
	@python3 src/main.py 1 "data/problema_real2.txt" 0.01 500 0.8 -hidden_layers 5 -val -wait 30

ejecuta_problema_real6:
	@python3 src/main.py 1 "data/problema_real6.txt" 0.1 5000 0.7 -hidden_layers 20 -norm